# App.yaml file for building on Google SDK
runtime: python311
entrypoint: python3 data.py
instance_class: F1  # Choose the instance class that suits your needs
automatic_scaling:  # You can also use manual or basic scaling
  target_cpu_utilization: 0.65
  min_instances: 1

handlers:
  - url: /.*
    script: auto

