# App.yaml file for building on Google SDK
runtime: python311
entrypoint: gunicorn -b :$PORT data:app # python3 data.py
instance_class: B4  # Choose the instance class that suits your needs
# automatic_scaling:  # You can also use manual or basic scaling
#   target_cpu_utilization: 0.65
  # min_instances: 1
  # max_instances: 10
basic_scaling:
  max_instances: 10
  idle_timeout: 60m
handlers:
  - url: /.*
    script: auto

